project:
  type: website
  output-dir: docs

website:
  title: "Davood Wadi"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Courses
        menu:        
          - text: MIT ADSP 
            url: https://professional.mit.edu/course-catalog/applied-data-science-program-leveraging-ai-effective-decision-making

          - text: MATH60629A 
            url: courses.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



