---
title: "MATH60629A - Machine Learning I (Fall 2023)"
resources:
    - "*.pdf"
format:
  html:
      toc: true
      toc-depth: 4

---
## Course Information

| [Contact Information](#contact-information) 	| [Bibliographic Sources](#bibliographic-sources) 	| [Class Information](#class-information) 	| [Evaluations](#evaluations) 	| [Session Materials](sessions.qmd) 	|


### Contact Information
::: {.callout-note appearance="minimal" collapse=true}

* **Davood Wadi**
    + Part-time Faculty Lecturer
    + <davood.wadi@hec.ca>
    + For office hours:
        - [Book meeting](https://calendly.com/davoodwadi/30min) 


* **Valérie Boucher**
    + Assistant to Academic Activities
    + <valerie.boucher@hec.ca>
    + 514-340-5670
    + Office: 4.632
    + Availability: 
        - Monday to Friday
        - 8:30 a.m. to 12 p.m. and 1 to 4:00 p.m.

 
* **Antonietta Florio**
    + Assistant to Academic Activities
    + <antonietta.florio@hec.ca>
    + 514-340-6473
    + Office: 4.632
    + Availability:
        - From Monday to Friday
        - From 8 am to 12 pm and from 1 pm to 4:30 pm 
* **Jennifer Caron**
    + Executive Assistant
    + <jennifer.caron@hec.ca>
    + 514-340-6473
    + Office: 4.632
    + Availability:
        - From Monday to Friday
        - From 8 am to 12 pm and from 1 pm to 4:30 pm
:::

### Bibliographic Sources
::: {.callout-note appearance="minimal" collapse=true}
* The Elements of Statistical Learning: Data Mining, Inference, and Prediction
    + [Available online](https://web.stanford.edu/~hastie/Papers/ESLII.pdf)

 
* Goodfellow, Ian . Deep learning , MIT Press
ISBN: 9780262035613
    + [Available online](https://www.deeplearningbook.org)
 
* Richard S. Sutton, Andrew G. Barto. A Bradford Book (2017 (in progress)). Reinforcement Learning: An Introduction Hardcover, 2nd edition ed., The MIT Press
    + [Available online](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&ved=0ahUKEwjAx8CEmsLbAhUFjlkKHd3hBnQQFggpMAE&url=http%3A%2F%2Fincompleteideas.net%2Fbook%2Fbookdraft2017nov5.pdf&usg=AOvVaw00kFmqVbFSdkU3PTkJMJrO)
 
* Murphy, Kevin (2012). Machine Learning: A Probabilistic Perspective, MIT Press
ISBN: 9780262018029
    + Available at the library
 
* Ricci, Francesco. Recommender systems handbook, Springer
ISBN: 148997637X
    + Available at the library
 
* Parsian, Mahmoud (2015). Data algorithms: recipes for scaling up with Hadoop and Spark, O'Reilly Media
ISBN: 9781491906156
    + Available at the library
 
* McKinney, Wes. Python for data analysis: data wrangling with Pandas, NumPy, and IPython, O'Reilly Media
    + Available at the library
 
* Bishop, Christopher (2006). Pattern Recognition and Machine Learning, Springer-Verlag New York
ISBN: 9780387310732
    + Available at the library
 
* Leskovec, Jurij. Mining of massive datasets, Cambridge University Press
    + Available at the library
 
* Grus, Joel. Data science from scratch, O'Reilly Media
    + Available at the library
 
* Sandy Ryza, Uri Laserson, Sean Owen, Josh Wills (2017). Advanced analytics with Spark: patterns from learning from data at scale, 2nd edition ed., O'Reilly Media
    + Available at the library
:::

### Class Information
::: {.callout-note appearance="minimal" collapse=false}
* Location
    + Building C-Ste-Cath, Room Groupe Cholette
* Time
    + Tuesdays, 3:30 PM - 6:30 PM EDT
:::

## Evaluations
### [Bonus] Class participation (5%)

To receive this 5% bonus point:

1. Prepare for each session's code before the class starts.
2. Log in to [deepnote](deepnote.com) with your **Full Name**.
3. During the coding exercises in class, add your answer to the questions as a *comment*.

### Homework (20%)
* Due on 24 October 2023
* Homework assignments are counted for 20% of your final grade.
* The homework should be done in jupyter notebook [here](MATH60629A_Homework.ipynb) or Google Colab [here](https://colab.research.google.com/github/davoodwadi/MATH60629A.A2023-MACHINE-LEARNING-I/blob/main/MATH60629A_Homework.ipynb).

* **Instructions**:
    + The homework is due by 11:59PM EST on the due date. 
    + Please upload a PDF version of your assignment on ZoneCours and insert the shareable link to your notebook in the same interface.
    + Homeworks must be completed individually. 
        - Discussion with others is okay, but you must write solutions yourself.
    + All code used to arrive at answers is submitted along with answers.
    + **Notes:**
        - Please provide your code answers in the code block under each question and verbal answers in text boxes assigned in the notebook (where applicable).
        - Please run the notebook before the submission so that the outputs are displayed.
        - Please make sure that your results are reproducible. You may use random seeds from `random` and `numpy` packages. For `scikit-learn` modules, you may use the `random_state` argument.

### Project (30%)
The aim of this project is to allow you to learn about machine learning by trying to solve a task with it.

First, select a question that can be answered using machine learning. I expect that your question will be about a model/algorithm or about an application. Then design a study that will try to answer your question. Your study must have an element of novelty. For example the novelty could be an extension or a variation of an existing algorithm or results of an existing method on a new dataset.

Your study should involve reading and understanding some background material. Your study must involve running some experiments. You are free to use (or not) any of the tools or models we have seen in class.

**Study plan**: *(1 upload per group)* Please submit a one-page summary of your proposed research question and study to ZoneCours. I will meet with each group to discuss study plans during the lecture on Week 9. I will send you a schedule the day before. We will probably only have about 15 minutes so please make sure that your study plan is clear and precise. You may also include questions that you would like us to discuss at the end of the document.

**The group report**: *(1 upload per group)* Your report must contain a description of the question you are trying to answer, a clear description of the model/algorithm you are studying, a survey of related work which proper references, an empirical section that reports your results, and a conclusion that summarizes your findings and (if pertinent) highlights possible future directions of investigation. Your report should be no longer than 10 pages in length (plus references) for pairs or 13 pages (plus references) for teams of three.

**The individual report**: *(1 upload per student)* You will also submit a brief individual report (at most one page), which will: (1) Describe the parts of the project you worked on (which machine learning methods you applied, which preprocessing steps you performed on the data, which parts of the term paper you wrote, who you worked with on what parts, etc.) and what parts of the project your teammates worked on. (2) What you learned from the project. The purpose of the individual report is to facilitate fair grading and to allow the instructor to understand well what you learned from the project.

Project Report (30%)

* Clarity/Relevance of problem statement and description of approach: 10%
* Discussion of relationship to previous work and references: 4%
* Design and execution of experiments: 10%
Figures/Tables/Writing: easily readable, properly labeled, * informative: 5%
* Indiviual report: 1%

#### Timeline

* Team Registration, due: **October 1**. Fill this [form](https://forms.gle/DkNsrh8xpYyU1kAh6).
* Study plan, due: **October 28** (by the end of the day EDT).
* Handing in: Through *ZoneCours*
* Project meeting, **October 31**
* Project Presentation, due: **December 1**. Upload the PDF of your poster/slides to *ZoneCours*.
* In-class Presentation, on **December 5**.
* Final individual report, due: **December 15**, 2023 (by the end of the day EDT).
    + Handing in: Through *ZoneCours* (per each team member).


### Project Presentation (10%)
Make a poster that describes your project. You can think of a poster as supporting material for your oral presentation (in that way it is similar to slides). It could also follow a similar structure: begin by motivating your work, then (quickly) highlight related work, talk in depth about your solution, then go into results (pictures and tables are good tools for that), finally conclude and perhaps mention one or two ideas for future work.

* Project Presentation (10%)
    + Clarity of presentation: 3%
    + Slide or Poster quality: 2%
    + Correctness: 2%
    + Answers to questions: 3%



### Final Exam (30%)
+ Dec 14, 2023
+ 9:00 am - 12:00 pm EDT
+ Location to be communicated

[Past exam - Fall 2018](exam_80629_A18.pdf)

### Capsule Quizzes (10%)
* In-class quizzes of the capsules
* Capsule quizzes are counted for 10% of your final grade.
    + Quiz 0, **TBA**.
    + Quiz 1, **TBA**.
    + Quiz 2, **TBA**.
    + Quiz 3, **TBA**.
    + Quiz 4, **TBA**.
    + Quiz 5, **TBA**.
    + Quiz 6, **TBA**.

## In-class Tools
* [Cups pacing webapp](https://ml1-pace.onrender.com/ml1)